[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"